//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_23TH0013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public int MaNguoiDung { get; set; }
        public string Hoten { get; set; }
        public string Email { get; set; }
        public string Dienthoai { get; set; }
        public string Matkhau { get; set; }
        public Nullable<int> IDQuyen { get; set; }
        public string Diachi { get; set; }
    }
}
